// import { Option } from '@/types';

// export type TimezoneOption = Option & { offset: string };

export type UTCOption = { label: 'UTC'; value: 'UTC'; offset: '0' };

export const TimezoneOptions = [
  { label: '-12:00 Etc/GMT-12', value: 'Etc/GMT-12', offset: '-12:00' },
  { label: '-11:00 Etc/GMT-11', value: 'Etc/GMT-11', offset: '-11:00' },
  { label: '-11:00 Pacific/Midway', value: 'Pacific/Midway', offset: '-11:00' },
  { label: '-10:00 America/Adak', value: 'America/Adak', offset: '-10:00' },
  {
    label: '-09:00 America/Anchorage',
    value: 'America/Anchorage',
    offset: '-09:00',
  },
  {
    label: '-09:00 Pacific/Gambier',
    value: 'Pacific/Gambier',
    offset: '-09:00',
  },
  {
    label: '-08:00 America/Dawson_Creek',
    value: 'America/Dawson_Creek',
    offset: '-08:00',
  },
  {
    label: '-08:00 America/Ensenada',
    value: 'America/Ensenada',
    offset: '-08:00',
  },
  {
    label: '-08:00 America/Los_Angeles',
    value: 'America/Los_Angeles',
    offset: '-08:00',
  },
  {
    label: '-07:00 America/Chihuahua',
    value: 'America/Chihuahua',
    offset: '-07:00',
  },
  {
    label: '-07:00 America/Phoenix',
    value: 'America/Phoenix',
    offset: '-07:00',
  },
  { label: '-07:00 America/Denver', value: 'America/Denver', offset: '-07:00' },
  { label: '-06:00 America/Belize', value: 'America/Belize', offset: '-06:00' },
  { label: '-06:00 America/Cancun', value: 'America/Cancun', offset: '-06:00' },
  {
    label: '-06:00 America/Chicago',
    value: 'America/Chicago',
    offset: '-06:00',
  },
  {
    label: '-06:00 Chile/EasterIsland',
    value: 'Chile/EasterIsland',
    offset: '-06:00',
  },
  { label: '-05:00 America/Bogota', value: 'America/Bogota', offset: '-05:00' },
  { label: '-05:00 America/Havana', value: 'America/Havana', offset: '-05:00' },
  {
    label: '-05:00 America/New_York',
    value: 'America/New_York',
    offset: '-05:00',
  },
  {
    label: '-05:00 America/Toronto',
    value: 'America/Toronto',
    offset: '-05:00',
  },
  {
    label: '-04:30 America/Caracas',
    value: 'America/Caracas',
    offset: '-04:30',
  },
  {
    label: '-04:00 America/Campo_Grande',
    value: 'America/Campo_Grande',
    offset: '-04:00',
  },
  {
    label: '-07:00 America/Edmonton',
    value: 'America/Edmonton',
    offset: '-07:00',
  },
  {
    label: '-04:00 America/Glace_Bay',
    value: 'America/Glace_Bay',
    offset: '-04:00',
  },
  {
    label: '-04:00 America/Goose_Bay',
    value: 'America/Goose_Bay',
    offset: '-04:00',
  },
  {
    label: '-04:00 America/Santiago',
    value: 'America/Santiago',
    offset: '-04:00',
  },
  { label: '-04:00 America/La_Paz', value: 'America/La_Paz', offset: '-04:00' },
  {
    label: '-03:00 America/Argentina/Buenos_Aires',
    value: 'America/Argentina/Buenos_Aires',
    offset: '-03:00',
  },
  {
    label: '-03:00 America/Montevideo',
    value: 'America/Montevideo',
    offset: '-03:00',
  },
  {
    label: '-03:00 America/Araguaina',
    value: 'America/Araguaina',
    offset: '-03:00',
  },
  {
    label: '-03:00 America/Godthab',
    value: 'America/Godthab',
    offset: '-03:00',
  },
  {
    label: '-03:00 America/Miquelon',
    value: 'America/Miquelon',
    offset: '-03:00',
  },
  {
    label: '-03:00 America/Sao_Paulo',
    value: 'America/Sao_Paulo',
    offset: '-03:00',
  },
  {
    label: '-03:30 America/St_Johns',
    value: 'America/St_Johns',
    offset: '-03:30',
  },
  {
    label: '-02:00 America/Noronha',
    value: 'America/Noronha',
    offset: '-02:00',
  },
  {
    label: '-08:00 America/Vancouver',
    value: 'America/Vancouver',
    offset: '-08:00',
  },
  {
    label: '-01:00 Atlantic/Cape_Verde',
    value: 'Atlantic/Cape_Verde',
    offset: '-01:00',
  },
  { label: 'GMT Europe/Belfast', value: 'Europe/Belfast', offset: '0' },
  { label: 'GMT Africa/Abidjan', value: 'Africa/Abidjan', offset: '0' },
  { label: 'GMT Europe/Dublin', value: 'Europe/Dublin', offset: '0' },
  { label: 'GMT Europe/Lisbon', value: 'Europe/Lisbon', offset: '0' },
  { label: 'GMT Europe/London', value: 'Europe/London', offset: '0' },
  { label: 'UTC', value: 'UTC', offset: '0' },
  { label: '+01:00 Africa/Algiers', value: 'Africa/Algiers', offset: '+01:00' },
  {
    label: '+01:00 Africa/Windhoek',
    value: 'Africa/Windhoek',
    offset: '+01:00',
  },
  {
    label: '+01:00 Atlantic/Azores',
    value: 'Atlantic/Azores',
    offset: '+01:00',
  },
  {
    label: '+01:00 Atlantic/Stanley',
    value: 'Atlantic/Stanley',
    offset: '+01:00',
  },
  {
    label: '+01:00 Europe/Amsterdam',
    value: 'Europe/Amsterdam',
    offset: '+01:00',
  },
  {
    label: '+01:00 Europe/Belgrade',
    value: 'Europe/Belgrade',
    offset: '+01:00',
  },
  {
    label: '+01:00 Europe/Brussels',
    value: 'Europe/Brussels',
    offset: '+01:00',
  },
  {
    label: '+02:00 Europe/Chisinau',
    value: 'Europe/Chisinau',
    offset: '+02:00',
  },
  { label: '+02:00 Africa/Cairo', value: 'Africa/Cairo', offset: '+02:00' },
  {
    label: '+02:00 Africa/Blantyre',
    value: 'Africa/Blantyre',
    offset: '+02:00',
  },
  { label: '+02:00 Asia/Beirut', value: 'Asia/Beirut', offset: '+02:00' },
  { label: '+02:00 Asia/Damascus', value: 'Asia/Damascus', offset: '+02:00' },
  { label: '+02:00 Asia/Gaza', value: 'Asia/Gaza', offset: '+02:00' },
  { label: '+02:00 Asia/Jerusalem', value: 'Asia/Jerusalem', offset: '+02:00' },
  {
    label: '+03:00 Africa/Addis_Ababa',
    value: 'Africa/Addis_Ababa',
    offset: '+03:00',
  },
  { label: '+03:00 Asia/Riyadh89', value: 'Asia/Riyadh89', offset: '+03:00' },
  { label: '+03:00 Europe/Minsk', value: 'Europe/Minsk', offset: '+03:00' },
  { label: '+03:00 Asia/Qatar', value: 'Asia/Qatar', offset: '+03:00' },
  { label: '+03:30 Asia/Tehran', value: 'Asia/Tehran', offset: '+03:30' },
  { label: '+04:00 Asia/Dubai', value: 'Asia/Dubai', offset: '+04:00' },
  { label: '+04:00 Asia/Yerevan', value: 'Asia/Yerevan', offset: '+04:00' },
  { label: '+04:00 Europe/Moscow', value: 'Europe/Moscow', offset: '+04:00' },
  { label: '+04:30 Asia/Kabul', value: 'Asia/Kabul', offset: '+04:30' },
  { label: '+05:00 Asia/Tashkent', value: 'Asia/Tashkent', offset: '+05:00' },
  { label: '+05:30 Asia/Kolkata', value: 'Asia/Kolkata', offset: '+05:30' },
  { label: '+05:45 Asia/Katmandu', value: 'Asia/Katmandu', offset: '+05:45' },
  { label: '+06:00 Asia/Dhaka', value: 'Asia/Dhaka', offset: '+06:00' },
  {
    label: '+06:00 Asia/Yekaterinburg',
    value: 'Asia/Yekaterinburg',
    offset: '+06:00',
  },
  { label: '+06:30 Asia/Rangoon', value: 'Asia/Rangoon', offset: '+06:30' },
  { label: '+07:00 Asia/Bangkok', value: 'Asia/Bangkok', offset: '+07:00' },
  {
    label: '+07:00 Asia/Novosibirsk',
    value: 'Asia/Novosibirsk',
    offset: '+07:00',
  },
  { label: '+08:00 Etc/GMT+8', value: 'Etc/GMT+8', offset: '+08:00' },
  { label: '+08:00 Asia/Hong_Kong', value: 'Asia/Hong_Kong', offset: '+08:00' },
  { label: '+08:00 Asia/Manila', value: 'Asia/Manila', offset: '+08:00' },
  {
    label: '+08:00 Asia/Krasnoyarsk',
    value: 'Asia/Krasnoyarsk',
    offset: '+08:00',
  },
  {
    label: '+08:00 Australia/Perth',
    value: 'Australia/Perth',
    offset: '+08:00',
  },
  {
    label: '+08:45 Australia/Eucla',
    value: 'Australia/Eucla',
    offset: '+08:45',
  },
  { label: '+09:00 Asia/Irkutsk', value: 'Asia/Irkutsk', offset: '+09:00' },
  { label: '+09:00 Asia/Seoul', value: 'Asia/Seoul', offset: '+09:00' },
  { label: '+09:00 Asia/Tokyo', value: 'Asia/Tokyo', offset: '+09:00' },
  {
    label: '+09:30 Australia/Adelaide',
    value: 'Australia/Adelaide',
    offset: '+09:30',
  },
  {
    label: '+09:30 Australia/Darwin',
    value: 'Australia/Darwin',
    offset: '+09:30',
  },
  {
    label: '+09:30 Pacific/Marquesas',
    value: 'Pacific/Marquesas',
    offset: '+09:30',
  },
  { label: '+10:00 Etc/GMT+10', value: 'Etc/GMT+10', offset: '+10:00' },
  {
    label: '+10:00 Australia/Brisbane',
    value: 'Australia/Brisbane',
    offset: '+10:00',
  },
  {
    label: '+10:00 Australia/Hobart',
    value: 'Australia/Hobart',
    offset: '+10:00',
  },
  { label: '+10:00 Asia/Yakutsk', value: 'Asia/Yakutsk', offset: '+10:00' },
  {
    label: '+10:30 Australia/Lord_Howe',
    value: 'Australia/Lord_Howe',
    offset: '+10:30',
  },
  {
    label: '+11:00 Asia/Vladivostok',
    value: 'Asia/Vladivostok',
    offset: '+11:00',
  },
  {
    label: '+11:30 Pacific/Norfolk',
    value: 'Pacific/Norfolk',
    offset: '+11:30',
  },
  { label: '+12:00 Etc/GMT+12', value: 'Etc/GMT+12', offset: '+12:00' },
  { label: '+12:00 Asia/Anadyr', value: 'Asia/Anadyr', offset: '+12:00' },
  { label: '+12:00 Asia/Magadan', value: 'Asia/Magadan', offset: '+12:00' },
  {
    label: '+12:00 Pacific/Auckland',
    value: 'Pacific/Auckland',
    offset: '+12:00',
  },
  {
    label: '+12:45 Pacific/Chatham',
    value: 'Pacific/Chatham',
    offset: '+12:45',
  },
  {
    label: '+13:00 Pacific/Tongatapu',
    value: 'Pacific/Tongatapu',
    offset: '+13:00',
  },
  {
    label: '+14:00 Pacific/Kiritimati',
    value: 'Pacific/Kiritimat',
    offset: '+14:00',
  },
];

export default {};
