export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_AND_TOKEN = 'SET_USER_AND_TOKEN';
export const SET_SETUP_COMPLETE = 'SET_SETUP_COMPLETE';
export const INCREMENT_REQUEST_ERRORS = 'INCREMENT_REQUEST_ERRORS';

export const SET_IS_PASSWORD_VALID = 'SET_IS_PASSWORD_VALID';

export const SET_SERVER_TIME_OFFSET = 'SET_SERVER_TIME_OFFSET';
export const SET_DEVICE_ORIENTATION = 'SET_DEVICE_ORIENTATION';
export const SET_NET_STATE = 'SET_NET_STATE';

export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
export const ATTEMPT_LOGIN_PENDING = 'ATTEMPT_LOGIN_PENDING';
export const ATTEMPT_LOGIN_ERROR = 'ATTEMPT_LOGIN_ERROR';
export const ATTEMPT_LOGIN_SUCCESS = 'ATTEMPT_LOGIN_SUCCESS';
export const CLEAR_LOGIN_MESSAGE = 'CLEAR_LOGIN_MESSAGE';

export const ATTEMPT_SIGNUP = 'ATTEMPT_SIGNUP';
export const ATTEMPT_SIGNUP_PENDING = 'ATTEMPT_SIGNUP_PENDING';
export const ATTEMPT_SIGNUP_ERROR = 'ATTEMPT_SIGNUP_ERROR';
export const ATTEMPT_SIGNUP_SUCCESS = 'ATTEMPT_SIGNUP_SUCCESS';
export const CLEAR_SIGNUP_MESSAGE = 'CLEAR_SIGNUP_MESSAGE';

export const APPLE_LOGIN = 'APPLE_LOGIN';
export const APPLE_LOGIN_PENDING = 'APPLE_LOGIN_PENDING';
export const APPLE_LOGIN_ERROR = 'APPLE_LOGIN_ERROR';
export const APPLE_LOGIN_SUCCESS = 'APPLE_LOGIN_SUCCESS';
export const CLEAR_APPLE_LOGIN_MESSAGE = 'CLEAR_APPLE_LOGIN_MESSAGE';

export const FACEBOOK_LOGIN = 'FACEBOOK_LOGIN';
export const FACEBOOK_LOGIN_PENDING = 'FACEBOOK_LOGIN_PENDING';
export const FACEBOOK_LOGIN_ERROR = 'FACEBOOK_LOGIN_ERROR';
export const FACEBOOK_LOGIN_SUCCESS = 'FACEBOOK_LOGIN_SUCCESS';
export const CLEAR_FACEBOOK_LOGIN_MESSAGE = 'CLEAR_FACEBOOK_LOGIN_MESSAGE';

export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_LOGIN_PENDING = 'GOOGLE_LOGIN_PENDING';
export const GOOGLE_LOGIN_ERROR = 'GOOGLE_LOGIN_ERROR';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const CLEAR_GOOGLE_LOGIN_MESSAGE = 'CLEAR_GOOGLE_LOGIN_MESSAGE';

export const SEND_OTP = 'SEND_OTP';
export const SEND_OTP_PENDING = 'SEND_OTP_PENDING';
export const SEND_OTP_ERROR = 'SEND_OTP_ERROR';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const CLEAR_SEND_OTP_MESSAGE = 'CLEAR_SEND_OTP_MESSAGE';

export const LOGIN_OTP = 'LOGIN_OTP';
export const LOGIN_OTP_PENDING = 'LOGIN_OTP_PENDING';
export const LOGIN_OTP_ERROR = 'LOGIN_OTP_ERROR';
export const LOGIN_OTP_SUCCESS = 'LOGIN_OTP_SUCCESS';
export const CLEAR_LOGIN_OTP_MESSAGE = 'CLEAR_LOGIN_OTP_MESSAGE';

export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_PENDING = 'FORGOT_PASSWORD_PENDING';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const RESET_FORGOT_PASSWORD_FETCH = 'RESET_FORGOT_PASSWORD_FETCH';
export const CLEAR_FORGOT_PASSWORD_MESSAGE = 'CLEAR_FORGOT_PASSWORD_MESSAGE';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_PENDING = 'RESET_PASSWORD_PENDING';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_RESET_PASSWORD_FETCH = 'RESET_RESET_PASSWORD_FETCH';
export const CLEAR_RESET_PASSWORD_MESSAGE = 'CLEAR_RESET_PASSWORD_MESSAGE';

export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const CHANGE_PASSWORD_PENDING = 'CHANGE_PASSWORD_PENDING';
export const CHANGE_PASSWORD_ERROR = 'CHANGE_PASSWORD_ERROR';
export const CHANGE_PASSWORD_SUCCESS = 'CHANGE_PASSWORD_SUCCESS';
export const CLEAR_CHANGE_PASSWORD_MESSAGE = 'CLEAR_CHANGE_PASSWORD_MESSAGE';

export const FETCH_ME = 'FETCH_ME';
export const FETCH_ME_PENDING = 'FETCH_ME_PENDING';
export const FETCH_ME_ERROR = 'FETCH_ME_ERROR';
export const FETCH_ME_SUCCESS = 'FETCH_ME_SUCCESS';

export const UPDATE_ME = 'UPDATE_ME';
export const UPDATE_ME_PENDING = 'UPDATE_ME_PENDING';
export const UPDATE_ME_ERROR = 'UPDATE_ME_ERROR';
export const UPDATE_ME_SUCCESS = 'UPDATE_ME_SUCCESS';
export const CLEAR_UPDATE_ME_MESSAGE = 'CLEAR_UPDATE_ME_MESSAGE';

export const UPDATE_MY_AVATAR = 'UPDATE_MY_AVATAR';
export const UPDATE_MY_AVATAR_PENDING = 'UPDATE_MY_AVATAR_PENDING';
export const UPDATE_MY_AVATAR_ERROR = 'UPDATE_MY_AVATAR_ERROR';
export const UPDATE_MY_AVATAR_SUCCESS = 'UPDATE_MY_AVATAR_SUCCESS';
export const CLEAR_UPDATE_MY_AVATAR_MESSAGE = 'CLEAR_UPDATE_MY_AVATAR_MESSAGE';

export const POST_SUPPORT_MESSAGE = 'POST_SUPPORT_MESSAGE';
export const POST_SUPPORT_MESSAGE_PENDING = 'POST_SUPPORT_MESSAGE_PENDING';
export const POST_SUPPORT_MESSAGE_ERROR = 'POST_SUPPORT_MESSAGE_ERROR';
export const POST_SUPPORT_MESSAGE_SUCCESS = 'POST_SUPPORT_MESSAGE_SUCCESS';
export const CLEAR_POST_SUPPORT_MESSAGE_MESSAGE =
  'CLEAR_POST_SUPPORT_MESSAGE_MESSAGE';

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const DELETE_ACCOUNT_PENDING = 'DELETE_ACCOUNT_PENDING';
export const DELETE_ACCOUNT_ERROR = 'DELETE_ACCOUNT_ERROR';
export const DELETE_ACCOUNT_SUCCESS = 'DELETE_ACCOUNT_SUCCESS';
export const CLEAR_DELETE_ACCOUNT_MESSAGE = 'CLEAR_DELETE_ACCOUNT_MESSAGE';

export const GET_USER_META = 'GET_USER_META';
export const GET_USER_META_PENDING = 'GET_USER_META_PENDING';
export const GET_USER_META_SUCCESS = 'GET_USER_META_SUCCESS';
export const GET_USER_META_ERROR = 'GET_USER_META_ERROR';
export const CLEAR_GET_USER_META_MESSAGE = 'CLEAR_GET_USER_META_MESSAGE';

export const GET_USER_META_KEY = 'GET_USER_META_KEY';
export const GET_USER_META_KEY_PENDING = 'GET_USER_META_KEY_PENDING';
export const GET_USER_META_KEY_SUCCESS = 'GET_USER_META_KEY_SUCCESS';
export const GET_USER_META_KEY_ERROR = 'GET_USER_META_KEY_ERROR';
export const CLEAR_GET_USER_META_KEY_MESSAGE =
  'CLEAR_GET_USER_META_KEY_MESSAGE';

export const SET_USER_META_KEY = 'SET_USER_META_KEY';
export const SET_USER_META_KEY_PENDING = 'SET_USER_META_KEY_PENDING';
export const SET_USER_META_KEY_SUCCESS = 'SET_USER_META_KEY_SUCCESS';
export const SET_USER_META_KEY_ERROR = 'SET_USER_META_KEY_ERROR';
export const CLEAR_SET_USER_META_KEY_MESSAGE =
  'CLEAR_SET_USER_META_KEY_MESSAGE';
